//stm32f407g discovery-1


/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdint.h>

int main(void)
{
	uint32_t *pClkCtrlReg =   (uint32_t*)0x40023830;
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t *pPortDOutReg =  (uint32_t*)0x40020C14;

	//1. enable the clock for GPOID peripheral in the AHB1ENR (SET the 3rd bit position)
	*pClkCtrlReg |= ( 1 << 3);

	//2. configure the mode of the IO pin as output
	//a. clear the 24th and 25th bit positions (CLEAR)
	*pPortDModeReg &= ~( 3 << 24);
	*pPortDModeReg &= ~( 3 << 22);
	*pPortDModeReg &= ~( 3 << 26);
	*pPortDModeReg &= ~( 3 << 28);
	*pPortDModeReg &= ~( 3 << 30);

	//b. make 24th bit position as 1 (SET)
	*pPortDModeReg |= ( 1 << 24);
	*pPortDModeReg |= ( 1 << 22);
	*pPortDModeReg |= ( 1 << 26);
	*pPortDModeReg |= ( 1 << 28);
	*pPortDModeReg |= ( 1 << 30);

	while(1)
	{

		for (uint8_t j = 11 ; j<=15 ; j++ )
			{


			*pPortDOutReg |= ( 1 << j);
			//*pPortDOutReg |= ( 1 << 12);
			//*pPortDOutReg |= ( 1 << 13);
			//*pPortDOutReg |= ( 1 << 14);

			for(uint32_t i=0 ; i < 300000 ; i++ );

			*pPortDOutReg &= ~( 1 << j);
			//*pPortDOutReg &= ~( 1 << 12);
			//*pPortDOutReg &= ~( 1 << 13);
			//*pPortDOutReg &= ~( 1 << 14);





			for(uint32_t i=0 ; i < 300000 ; i++ );


			}


	}

}


